---
title: "Research4"
author: "Austin Castelo and Isaac Golberg"
date: "May 2, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(MASS)
library(nlme)
library(mAr)
```


```{r, include=FALSE}
T_Bills_3_month_1934_2018 <- read_excel("C:/Users/caste/Desktop/PSTAT199/T-Bills.xlsx")
EconData <- read.csv("C:/Users/caste/Desktop/PSTAT199/EconData.csv")
EconData$Inflation[1] <- 0.024
EconData$Inflation = EconData$Inflation/12
for (i in 1:1011){
  EconData$AdjInf[i] <- (1+sum(EconData$Inflation[i:1011]))/(1+EconData$Inflation[1011])}


```


```{r, include=FALSE}
EconData$AdjustedPE <- EconData$S.P.500.PE.Ratio.by.Month./(1+ EconData$Inflation)
Pt <- EconData$AdjustedPE[1:1011]
P_ <- mean(Pt)

tb <- T_Bills_3_month_1934_2018$TB3MS
Rt <- (tb/12 - EconData$Inflation[1:1011])
R_ <- mean(Rt)
```

 
```{r, include=FALSE}
pHat <- Pt - P_
rHat <- Rt - R_

```


```{r, include=FALSE}
EconData$AdjustedSP <- EconData$S.P.500.Real.Price.by.Month/EconData$AdjInf
SP <- EconData$AdjustedSP[1:1014]
g <- (1/1010)*log(SP[1]/SP[1011])
gmat <- matrix(nrow = 1011, ncol = 1)
for (i in 1:1011){
  gmat[i] <- g
}
```

```{r, include=FALSE}
delT <- matrix(nrow = 1012, ncol = 1)
for(i in 1:1012){delT[i] = log(SP[i]/SP[i+1])}
delT = delT[-1012,]
```



```{r, include=FALSE}
mod <- lm(delT ~ gmat + (pHat) + (rHat))
summary(mod)

```

```{r, include=FALSE}
yhat <- fitted(mod)
e <- delT - yhat
plot(yhat, e[1:1011], main = "Residuals vs Fit v1")
```

```{r, include=FALSE}
qqnorm(e)
qqline(e)
```

```{r, include=FALSE}
mod2 <- matrix(c(rHat, pHat), nrow = 1011, ncol = 2)
mod3 <- mAr.est(mod2, 1)
AHat <- mod3$AHat
CHat <- mod3$CHat
mAr.eig(AHat, CHat)
AHat
```
#Regression and 2D AR(1) Results results t = 120

```{r, echo=FALSE}
nres <- matrix(nrow = 1, ncol = 10)
for(j in 1:(1012-120)){delT[j] = log(SP[j]/SP[j+120])}
  delT <- delT/120
  lmod <- summary(lm(delT~ pHat+rHat ))
  nres[1,1] <-  lmod$coefficients[1,1]
  nres[1,2] <-  lmod$coefficients[1,2]
  nres[1,3] <-  lmod$coefficients[2,1]
  nres[1,4] <-  lmod$coefficients[2,2]
  nres[1,5] <-  lmod$coefficients[1,4]
  nres[1,6] <-  lmod$coefficients[2,4]
  nres[1,7] <-  lmod$coefficients[3,1]
  nres[1,8] <- lmod$coefficients[3,2]
  nres[1,9] <- lmod$coefficients[3,4]
  nres[1,10] <- sigma(lm(delT~ pHat+rHat ))
  nres <- as.data.frame(nres)
  colnames(nres) <- c("g","g Std. Error", "alpha estimate", "alpha Estimate Std. Error", "g p-value","alpha p-value", "beta estimate", "beta std. error", "beta p-value", "Residual standard error (error for stocks?)")
  print("g")
  nres$g
  print("g Std. Error") 
  nres$`g Std. Error`
  print("alpha estimate")
  nres$`alpha estimate`
  print("alpha estimate std. error")
  nres$`alpha Estimate Std. Error`
  print("g p-value")
  nres$`g p-value`
  print("alpha p-value")
  nres$`alpha p-value`
  print("beta estimate")
  nres$`beta estimate
  print("beta estimate std. error")`
  nres$`beta std. error`
  print("beta p-value")
  nres$`beta p-value`
  print("Residual standard error (error for stocks?)")
  nres$`Residual standard error (error for stocks?)`
```

###2x2 regression matrix
```{r}
AHat
```

###2x2 covariance matrix
```{r}
CHat
```
